project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Media Coverage on Israel-Palestine Conflict"
  author:
    - Tanya Lim (tjl2150)
    - Ernest Salim (es4281)
  repo-url: https://github.com/Nesto17/israel-palestine-media-analysis
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: lux
    code-fold: true


